### ISSUE TITLE
getViewState() returns null if moxy-compiler has "provided" scope

### ISSUE THREAD

**Issue by ekursakov** [Arello-Mobile/Moxy#101]
Hi!
When moxy-compiler integrated as `provided 'com.arello-mobile:moxy-compiler:1.4.6' ` then getViewState() method in presenters returns null on non-clean builds.
Solution I found is to change scope from `provided` to `annotationProcessor`.

Small test project: https://github.com/ekursakov/moxytest

Steps to reproduce:
1. Launch app
2. Change something in code (for example message in MainActivity)
3. Launch app again
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.moxytest/com.example.moxytest.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.example.moxytest.MainView.doSomething()' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.example.moxytest.MainView.doSomething()' on a null object reference
                                                     at com.example.moxytest.MainPresenter.onFirstViewAttach(MainPresenter.java:10)
                                                     at com.arellomobile.mvp.MvpPresenter.attachView(MvpPresenter.java:49)
                                                     at com.arellomobile.mvp.MvpDelegate.onAttach(MvpDelegate.java:121)
                                                     at com.arellomobile.mvp.MvpAppCompatActivity.onStart(MvpAppCompatActivity.java:29)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                     at android.app.Activity.performStart(Activity.java:6253)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ```

**Comment by senneco** [comment]
Deleted `provided` from readme ;)
