### ISSUE TITLE
NPE in MvpDelegate onDetach()

### ISSUE THREAD

**Issue by Jeevuz** [Arello-Mobile/Moxy#125]
Crashed on version 1.4.6, but I think it is still possible.

The presenters list is null somewhat in the onDetach().

Here is the log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.arellomobile.mvp.MvpDelegate.onDetach(MvpDelegate.java:135)
       at com.arellomobile.mvp.MvpAppCompatFragment.onSaveInstanceState(MvpAppCompatFragment.java:49)
       at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2356)
```

**Comment by xanderblinov** [comment]
Hey, @Jeevuz
Thanks for your issue. Please accept my apology for the delayed reply.
Is it reproducible bag. Looks like onDetach callback has performed before onCreate. Do you have some not typical fragment transaction or stuff like this?

**Comment by Jeevuz** [comment]
Hi!
To be honest I don't remember where was this bug :) But we have experienced the same problem when lateinit property was not initialized in onDestroy, because there was no onCreate call before it. It was fragment with the mapView. Really don't know when this happens. Our solution was just to remove the lateinit, make the property nullable and handle nulls.

**Comment by xanderblinov** [comment]
Sounds very strange. Could you please provide some additional info about this problem? For instance, provide log from all threads from crashlitics or add special event at analytic to get info about Fragment and it's parent state

**Comment by Jeevuz** [comment]
I think I found the reason. This crash is from the place with the similar problem I described:

```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property mapView has not been initialized
       at ru.mobileup.businessnavigator.ui.base.BaseMapFragment.onDestroy(BaseMapFragment.kt:124)
       at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
       at ru.terrakok.cicerone.android.SupportFragmentNavigator.backToRoot(SupportFragmentNavigator.java:112)
       at ru.terrakok.cicerone.android.SupportFragmentNavigator.applyCommand(SupportFragmentNavigator.java:89)
       at ru.terrakok.cicerone.android.SupportAppNavigator.applyCommand(SupportAppNavigator.java:63)
       at ru.terrakok.cicerone.CommandBuffer.executeCommand(CommandBuffer.java:43)
       at ru.terrakok.cicerone.CommandBuffer.setNavigator(CommandBuffer.java:26)
       at ru.mobileup.businessnavigator.ui.main.MainActivity.onResumeFragments(MainActivity.kt:47)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at android.app.Activity.performResume(Activity.java:6432)
```

The problem shows up in conjunction with the Cicerone lib. Activity starts and CommandBuffer has command (I bet it's `Router.newRootScreen()` with `BackTo(null)` command inside) that causes `backToRoot()` method call, which causes call to the `executePendingTransactions()`. FragmentManager adds some optimization to not start the intermediate fragments. And all this causes the call to `onDestroy()` without calling `onCreate()` in advance.

**Comment by Jeevuz** [comment]
So this is really possible case and should be handled by the library.

**Comment by Jeevuz** [comment]
Hi guys! I tried to reproduce this issue for our library RxPM with no success. So I think this is really rare case and also has workarounds (null check, lateinit::isInitialized). 
I'm closing this one.

**Comment by xanderblinov** [comment]
You are right, @Jeevuz. It should be fixed. See https://github.com/moxy-community/Moxy/pull/4
