### ISSUE TITLE
Android-apt most recent version support

### ISSUE THREAD

**Issue by vfarafonov** [Arello-Mobile/Moxy#13]
Hi.
I am playing with your lib and see some strange behaivour when building from the command line using gradlew. Executing `gradlew assembleDebug` will fail if I have android-apt version 1.8 (most recent for now) declared. Stacktrace:
```
Caused by: java.lang.NoSuchFieldError: DEFAULT
        at com.arellomobile.mvp.compiler.MvpCompiler.process(MvpCompiler.java:85)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        ... 79 more
```
Build from Android Studio's "Run" command is successfull every time.
Everything is fine when I switch android-apt to ver. 1.4. 
P.S. Lib looks helpful - great job

**Comment by vfarafonov** [comment]
The problem here is the JDK version used to build module. If I use 1.7 - build fails. Need to use 1.8.
You can tell gradlew to use specific version of JDK by setting it up in _gradle.properties_ or by adding parameter to the terminal command like:
`gradlew -Dorg.gradle.java.home="C:\Program Files\Java\jdk1.8.0_40" assembleDebug`
Issue can be closed. Probably you should add this info to the readme.md

**Comment by xanderblinov** [comment]
Vladimir, thank you for interesting in Moxy and quick solution for issue! Solution will be add to common question section

**Comment by xanderblinov** [comment]
[FAQ section](https://github.com/Arello-Mobile/Moxy/wiki/FAQ)
