### ISSUE TITLE
Ошибка при запуске тестов с Moxy и Kotlin

### ISSUE THREAD

**Issue by LionZXY** [Arello-Mobile/Moxy#149]
Здравствуйте. Решил написать тесты и при запуске онных приложение крашиться:
```
kotlin.UninitializedPropertyAccessException: lateinit property presenter has not been initialized
at com.togezzer.android.ui.splashscreen.view.SplashscreenActivity.onCreate(SplashscreenActivity.kt:30)
at android.app.Activity.performCreate(Activity.java:6723)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Хотя в релизе все инджектиться нормально. 
Вот мой build.gradle:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.togezzer.android"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 'git rev-list master --count --no-merges'.execute().text.toInteger()
        versionName "1.0"
        multiDexEnabled true
        manifestPlaceholders = [HOCKEYAPP_APP_ID: "17f9e44d70064bb39232d1591675eb14"]
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation":
                                     "$projectDir/schemas".toString()]
            }
        }
    }

    signingConfigs {
        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_STORE_PASSWORD
        }

        debug {

        }
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
            signingConfig signingConfigs.debug
            buildConfigField "String", "API_URL", '"http://api-test.togezzer.net/v1/"'
            buildConfigField "String", "SOCKET_URL", '"ws://rest.togezzer.net:8081/"'
        }

        release {
            buildConfigField "String", "API_URL", '"http://api.togezzer.net/v1/"'
            buildConfigField "String", "SOCKET_URL", '"ws://rest.togezzer.net:8080/"'
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}

kapt {
    generateStubs = true
}

ext.moxyVersion = '1.5.3'
ext.daggerVersion = '2.10'
ext.retrofitVersion = '2.3.0'
ext.supportVersion = '25.3.1'
ext.rxbindingVersion = '2.0.0'
ext.roomVersion = '1.0.0-alpha3'
ext.glideVersion = '4.0.0-RC1'
ext.firebaseFCMVersion = '11.0.1'
ext.searchViewVersion = '2.1.1'
ext.stethoVersion = '1.5.0'
ext.matisseVersion = '0.5.0-alpha4'
ext.leakCanaryVersion = '1.5.1'

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.android.support:appcompat-v7:$supportVersion"
    compile "com.android.support:design:$supportVersion"
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile "com.android.support:cardview-v7:$supportVersion"
    compile 'net.hockeyapp.android:HockeySDK:4.0.0'
    testCompile 'junit:junit:4.12'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

    compile "com.github.arimorty:floatingsearchview:$searchViewVersion"

    // Firebase:
    compile "com.google.firebase:firebase-messaging:$firebaseFCMVersion"
    compile 'com.firebase:firebase-jobdispatcher:0.7.0'

    compile "com.arello-mobile:moxy:$moxyVersion"
    annotationProcessor "com.arello-mobile:moxy-compiler:$moxyVersion"
    compile "com.arello-mobile:moxy-android:$moxyVersion"
    compile "com.arello-mobile:moxy-app-compat:$moxyVersion"
    kapt "com.arello-mobile:moxy-compiler:$moxyVersion"

    compile "com.jakewharton.rxbinding2:rxbinding-kotlin:$rxbindingVersion"
    compile "com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin:$rxbindingVersion"
    compile "com.jakewharton.rxbinding2:rxbinding-design-kotlin:$rxbindingVersion"
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'com.jakewharton.rxrelay2:rxrelay:2.0.0'
    compile 'com.jakewharton.timber:timber:4.5.1'
    compile "com.zhihu.android:matisse:$matisseVersion"
    compile 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.4@aar'

    compile "com.google.dagger:dagger:$daggerVersion"
    kapt "com.google.dagger:dagger-compiler:$daggerVersion"
    compile "com.google.dagger:dagger-android-support:$daggerVersion"

    compile "com.facebook.stetho:stetho:$stethoVersion"
    compile "com.facebook.stetho:stetho-okhttp3:$stethoVersion"
    compile "com.facebook.stetho:stetho-urlconnection:$stethoVersion"

    compile 'com.google.code.gson:gson:2.8.1'

    compile "com.squareup.retrofit2:retrofit:$retrofitVersion"
    compile "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    compile "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
    compile 'com.squareup.okhttp3:logging-interceptor:3.8.0'

    compile 'ru.terrakok.cicerone:cicerone:1.2.1'

    compile "android.arch.persistence.room:runtime:$roomVersion"
    compile "android.arch.persistence.room:rxjava2:$roomVersion"
    kapt "android.arch.persistence.room:compiler:$roomVersion"

    compile "com.github.bumptech.glide:glide:$glideVersion"
    kapt "com.github.bumptech.glide:compiler:$glideVersion"
    compile 'com.github.MaxMyalkin:MaterialChipsInput:dd9490cd9c'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'

    debugCompile "com.squareup.leakcanary:leakcanary-android:$leakCanaryVersion"
    releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$leakCanaryVersion"
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'

    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
        exclude group: 'com.google.code.findbugs'
    }
}
repositories {
    mavenCentral()
}

apply plugin: 'com.google.gms.google-services'
```

Использую самую новую версию, судя по тому, что приложение дошло до этого момента, аннотации тем же даггером обрабатываются.

**Comment by LionZXY** [comment]
Создал тестовый проект, в котором повторил краш:
https://github.com/LionZXY/Kotlin-Espresso-sample

**Comment by xanderblinov** [comment]
Добрый день, @LionZXY приносим извинения за то, что долго не отвечали.

Скажите, пожалуйста, какие классы генерируются? Создался ли класс `*имя класса презентера*$$PresentersBinder` ?

**Comment by topjavaproger** [comment]
Такая же проблема при запуске тестов espresso.

Создается папка `build/generated/source/kapt/**debugAndroidTest**/com.arellomobile.mvp` и в ней `MoxyReflector` со статик блоком:

```
static {
		sViewStateProviders = new HashMap<>();
		
		sPresenterBinders = new HashMap<>();
		
		sStrategies = new HashMap<>();
	}
```

В то время как в `build/generated/source/kapt/**debug**/com.arellomobile.mvp` c `MoxyReflector` все нормально.

Добавление-удаление следующих строк на результат не влияет :(
```
kaptAndroidTest 'com.arello-mobile:moxy-compiler:1.5.3'
testAnnotationProcessor 'com.arello-mobile:moxy-compiler:1.5.3'
```
