### ISSUE TITLE
Ошибка при отложенной инициализации презентера

### ISSUE THREAD

**Issue by ShadyRover** [Arello-Mobile/Moxy#168]
Я загрузил проект из репозитория и запустил sample-kotlin
В примере используется отложенная инициализация презентера,
после нажатия на главный экран приложение падает с ошибкой:
` Process: com.arellomobile.mvp.sample.kotlin, PID: 6110
                                                                                  kotlin.UninitializedPropertyAccessException: lateinit property dialogPresenter has not been initialized
                                                                                      at com.arellomobile.mvp.sample.kotlin.MainActivity.getDialogPresenter(MainActivity.kt:19)
                                                                                      at com.arellomobile.mvp.sample.kotlin.MainActivity$onCreate$1.onClick(MainActivity.kt:33)
                                                                                      at android.view.View.performClick(View.java:6256)
                                                                                      at android.view.View$PerformClick.run(View.java:24697)
                                                                                      at android.os.Handler.handleCallback(Handler.java:789)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

Использую последнии версии библиотек:
`dependencies {
    compile 'com.android.support:appcompat-v7:25.0.0'

    compile 'com.arello-mobile:moxy:1.5.3'
    compile 'com.arello-mobile:moxy-app-compat:1.5.3'
    kapt 'com.arello-mobile:moxy-compiler:1.5.3'

    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}`

**Comment by senneco** [comment]
Интересная ошибка, ни разу такой не ловил. У вас до сих пор она проявляется?

**Comment by september669** [comment]
`8118-8118 E/AndroidRuntime: FATAL EXCEPTION: main
                            Process: com.a7glyphs.testtask, PID: 8118
                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.a7glyphs.testtask/com.a7glyphs.testtask.ui.LoginActivity}: kotlin.UninitializedPropertyAccessException: lateinit property mPresenter has not been initialized
                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                at android.os.Looper.loop(Looper.java:135)
                                at android.app.ActivityThread.main(ActivityThread.java:5221)
                                at java.lang.reflect.Method.invoke(Native Method)
                                at java.lang.reflect.Method.invoke(Method.java:372)
                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                             Caused by: kotlin.UninitializedPropertyAccessException: lateinit property mPresenter has not been initialized
                                at com.a7glyphs.testtask.ui.LoginActivity.onCreate(LoginActivity.kt:35)
                                at android.app.Activity.performCreate(Activity.java:5933)
                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                at android.os.Looper.loop(Looper.java:135) 
                                at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                at java.lang.reflect.Method.invoke(Native Method) 
                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
`

Тоже самое, только на своем проекте с теми же версиями в AS 3.0.1
kotlin_version = '1.1.60'

**Comment by senneco** [comment]
А можете показать вашу LoginActivity и build.gradle, в котором прописаны зависимости?

**Comment by september669** [comment]
`class LoginActivity : AppCompatActivity(), LoginView, AnkoLogger {

    @InjectPresenter(type = PresenterType.GLOBAL)
    lateinit var mPresenter: LoginPresenter

    @ProvidePresenter(type = PresenterType.GLOBAL)
    fun provideDialogPresenter() = LoginPresenter()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        info { "LoginPresenter $mPresenter" }

        btn_login.setBackgroundColor(ContextCompat.getColor(baseContext, R.color.colorLoginBtn))
        btn_login.setOnClickListener({ mPresenter.onLogin() })

        txt_login.afterTextChanged { mPresenter.onUserNameReady(it) }
        txt_email.afterTextChanged { mPresenter.onUserEmailReady(it) }
    }


    override fun swichLoginPossible(isPossible: Boolean) {
        info ("swichLoginPossible: $isPossible")
        btn_login.isActivated = isPossible
    }

    override fun hideDialog() {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

}
`

`kapt {
    generateStubs = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    //Anko
    compile "org.jetbrains.anko:anko-commons:$anko_version"

    //Google
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

    //Moxy
    kapt 'com.arello-mobile:moxy-compiler:1.5.3'
    compile 'com.arello-mobile:moxy:1.5.3'
    compile 'com.arello-mobile:moxy-app-compat:1.5.3'


    //  UI
    //Morphing Button
    compile 'com.github.dmytrodanylyk:android-morphing-button:98a4986e56'
}
`

**Comment by senneco** [comment]
Ваша `LoginActivity ` не наследуется от `MvpAppCompatActivity`

**Comment by senneco** [comment]
И не стоит делать LoginPresenter глобальным

**Comment by september669** [comment]
Уже не первый раз на этом втупляю :(  Спасибо!
