### ISSUE TITLE
How do you use dagger 2 injection with Moxy

### ISSUE THREAD

**Issue by maruf89** [Arello-Mobile/Moxy#18]
Trying to use the @InjectPresenter in the Views and @InjectViewState preceding the presenter classes but my presenter classes also need to inject modules of their own which I'm doing via the constructor but I get this error

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jackthreads.android/com.jackthreads.android.activities.PageActivity}: java.lang.IllegalStateException: Unable to instantiate class com.jackthreads.android.presenters.PagePresenter: make sure class name exists, is public, and has an empty constructor that is public
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
     at android.app.ActivityThread.access$900(ActivityThread.java:172)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:5835)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
  Caused by: java.lang.IllegalStateException: Unable to instantiate class com.jackthreads.android.presenters.PagePresenter: make sure class name exists, is public, and has an empty constructor that is public
     at com.arellomobile.mvp.DefaultPresenterFactory.createPresenter(DefaultPresenterFactory.java:30)
     at com.arellomobile.mvp.DefaultPresenterFactory.createPresenter(DefaultPresenterFactory.java:11)
     at com.arellomobile.mvp.MvpProcessor.getMvpPresenter(MvpProcessor.java:125)
     at com.arellomobile.mvp.MvpProcessor.getMvpPresenters(MvpProcessor.java:177)
     at com.arellomobile.mvp.MvpDelegate.onCreate(MvpDelegate.java:110)
     at com.jackthreads.android.activities.MvpAppCompatActivity.onCreate(MvpAppCompatActivity.java:15)
```

Searching Moxy and Dagger 2 brings up nothing and it seems like they're messing each other up.

**Comment by senneco** [comment]
Moxy says that it can't to instantiate class com.jackthreads.android.presenters.PagePresenter. Are sure class is public, and has an empty constructor that is public?

You could make gist, then I can help you ;)

**Comment by senneco** [comment]
[Here](https://github.com/Arello-Mobile/MoxySample/blob/master/app/src/main/java/com/arellomobile/github/mvp/presenters/SignInPresenter.java) you can see, ho to use injection in presenter class.

**Comment by maruf89** [comment]
Unfortunately I had to move forward without using Moxy InjectPresenter/ViewState annotations as I couldn't get it working. I'll have to post my setup again. The problem I was having after injecting like in your example was that I was getting uninstantiated injected objects. I realize that doesn't help much until I get a code sample up, I'll try to get a simple example sometime soon.

**Comment by senneco** [comment]
Sorry, but I don't understand. Are you need help?

**Comment by morder** [comment]
It's very unuseful to inject objects without constructor like this
```
@Inject
public ProfilePresenter(DataR dataR, MainN n, AuthM authM, BroadcastM broadcastM) {
}
```
because we need to call 
YourApplication.getComponent().inject(this);
but we have complex dagger2 structure with many modules

**Comment by morder** [comment]
It will be good to inject presenters by some call in views, like
```
MvpFacade.getInstance().getMvpProcessor().addPresenter(View view, Presenter presenter,
PresenterType type);
```

**Comment by senneco** [comment]
No, it's wrong way for inject presenter. You can use @ProvidePresenter to provide your Presenter's instance. See more about this [here](https://github.com/Arello-Mobile/Moxy/wiki/Provides-Presenter-and-its-Tag) and [here](https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/adapters/RepositoriesAdapter.java#L155-L158).

**Comment by morder** [comment]
Thanks, it's helps :)

**Comment by vkotovv** [comment]
Related question - #100
