### ISSUE TITLE
Crash with NPE in AddToEndSingleStrategy.java line 25

### ISSUE THREAD

**Issue by tridetch** [Arello-Mobile/Moxy#219]
Есть большая вью с примерно 80 методами в какой то момент в крэшлитике стал приходить такой крэш и появляется все чаще и чаще

AddToEndSingleStrategy.java line 25
com.arellomobile.mvp.viewstate.strategy.AddToEndSingleStrategy.beforeApply

 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.arellomobile.mvp.viewstate.strategy.AddToEndSingleStrategy.beforeApply(AddToEndSingleStrategy.java:25)
       at com.arellomobile.mvp.viewstate.ViewCommands.beforeApply(ViewCommands.java:27)
       at online.cartrek.app.presentation.view.MapView$$State.updateAbonentTime(MapView$$State.java:1217)
       at online.cartrek.app.presentation.presenter.MapPresenter$4.run(MapPresenter.java:294)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)

Moxy version 1.5.3

**Comment by tridetch** [comment]
И еще такие крэши

AddToEndSingleStrategy.java line 31
com.arellomobile.mvp.viewstate.strategy.AddToEndSingleStrategy.beforeApply

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=15; index=15
       at java.util.ArrayList.add(ArrayList.java:468)
       at com.arellomobile.mvp.viewstate.strategy.AddToEndSingleStrategy.beforeApply(AddToEndSingleStrategy.java:31)
       at com.arellomobile.mvp.viewstate.ViewCommands.beforeApply(ViewCommands.java:27)
       at online.cartrek.app.presentation.view.MapView$$State.triggeredDistance(MapView$$State.java:1169)
       at online.cartrek.app.presentation.presenter.MapPresenter$3.run(MapPresenter.java:256)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)

**Comment by jordan1997** [comment]
@tridetch можна пример View Interface

**Comment by tridetch** [comment]
@jordan1997 https://gist.github.com/tridetch/d889f0f33d7d202529ef97e5e4e80139

**Comment by jordan1997** [comment]
@tridetch Do you have some problems with the version `1.5.5`? Or another way of this question, Why you do not use `1.5.5`?

**Comment by jordan1997** [comment]
@tridetch I created following project based on your interface 
https://github.com/jordan1997/MoxyBigView

And I cannot reproduce the bug. I added a test into that project which rotates the device 500 times, and nothing happens.

I think it happens because of some of the view detach, by Set doesn't update immediately. For my opinion problem in the following lines:
```
        protected ViewCommands<View> mViewCommands = new ViewCommands<>();
	protected Set<View> mViews;
	protected Set<View> mInRestoreState;
	protected Map<View, Set<ViewCommand<View>>> mViewStates;
```
Maybe, we need to use volatile for following fields. @senneco What do you think about this?

@tridetch Maybe, you can make some changes in the by sample project, for reproducing your issue.

**Comment by formatBCE** [comment]
I have same issue. At some point, i have a lot of updates using one of view methods with AddToEndSingleStrategy. No rotations or any other view detaches on that point, but still crash.
