### ISSUE TITLE
 java.lang.NoSuchMethodError when call MvpAppCompatFragment.onDestroy()

### ISSUE THREAD

**Issue by SergiyKorotun** [Arello-Mobile/Moxy#27]
java.lang.NoSuchMethodError: No virtual method getActivity()Landroid/app/Activity; in class Lcom/arellomobile/mvp/MvpAppCompatFragment; or its super classes (declaration of 'com.arellomobile.mvp.MvpAppCompatFragment' appears in ...)
                                                                                 at com.arellomobile.mvp.MvpAppCompatFragment.onDestroy(MvpAppCompatFragment.java:40)
                                                                                 at android.support.v4.app.Fragment.performDestroy(Fragment.java:2322)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1240)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2186)
                                                                                 at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
                                                                                 at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:388)
                                                                                 at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
                                                                                 at com.arellomobile.mvp.MvpAppCompatActivity.onDestroy(MvpAppCompatActivity.java:26)
                                                                                 at android.app.Activity.performDestroy(Activity.java:6169)
                                                                                 at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
                                                                                 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
                                                                                 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
                                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by CherryPerry** [comment]
Тоже такую ошибку словил. Может связано с тем, что Stub описан неправильно? Все-таки getActivity у саппортовского фрагмента возвращает FragmentActivity, а не Activity.

**Comment by senneco** [comment]
Hot bug. Began to fix it.

**Comment by senneco** [comment]
Fixed in Moxy 1.0.2. Thanks ;)

**Comment by SergiyKorotun** [comment]
@senneco Thank you for the quick fix!
