### ISSUE TITLE
jack and annotationProcessor

### ISSUE THREAD

**Issue by fisher3421** [Arello-Mobile/Moxy#52]
I try use jack, java8 and annotationProcessor. But I get error
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1931)
        at com.arellomobile.mvp.compiler.Util.getFullClassName(Util.java:105)
        at com.arellomobile.mvp.compiler.Util.getFullClassName(Util.java:97)
        at com.arellomobile.mvp.compiler.PresenterInjectorRules.checkEnvironment(PresenterInjectorRules.java:70)
        at com.arellomobile.mvp.compiler.PresenterInjectorRules.checkAnnotation(PresenterInjectorRules.java:44)
        at com.arellomobile.mvp.compiler.MvpCompiler.checkInjectors(MvpCompiler.java:115)
        at com.arellomobile.mvp.compiler.MvpCompiler.throwableProcess(MvpCompiler.java:96)
        at com.arellomobile.mvp.compiler.MvpCompiler.process(MvpCompiler.java:84)
```

To reproduce modify build.gradle of sample-github like this

```
apply plugin: 'com.android.application'

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        applicationId "com.arellomobile.mvp.sample.github"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        jackOptions {
            enabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError false
    }
}

def support = '25.0.0'
def retrofit = '2.1.0'
def dagger = '2.7'
def butterKnife = "8.4.0"

dependencies {
    testCompile "junit:junit:4.12"
    compile "com.android.support:appcompat-v7:$support"
    compile "com.android.support:design:$support"

    compile "com.j256.ormlite:ormlite-core:4.48"
    compile "com.j256.ormlite:ormlite-android:4.48"

    compile "com.google.code.gson:gson:2.5"

    compile "com.jakewharton:butterknife:$butterKnife"

    compile "com.squareup.retrofit2:retrofit:$retrofit"
    compile "com.squareup.retrofit2:converter-gson:$retrofit"
    compile "com.squareup.retrofit2:adapter-rxjava:$retrofit"
    compile "com.squareup.picasso:picasso:2.5.2"
    compile "com.squareup:otto:1.3.8"

    compile "io.reactivex:rxjava:1.1.0"
    compile "io.reactivex:rxandroid:1.1.0"

    compile "com.google.dagger:dagger:$dagger"
    provided "org.glassfish:javax.annotation:10.0-b28"

    annotationProcessor "com.jakewharton:butterknife-compiler:$butterKnife"
    annotationProcessor "com.google.dagger:dagger-compiler:$dagger"

    testCompile "junit:junit:4.12"
    testCompile "org.mockito:mockito-all:1.10.19"
    testCompile "org.hamcrest:hamcrest-all:1.3"
    testCompile "org.robolectric:robolectric:3.1-rc1"

    compile 'com.arello-mobile:moxy:1.2.0'
    annotationProcessor 'com.arello-mobile:moxy-compiler:1.2.0'
}
```

**Comment by senneco** [comment]
Fixed at moxy 1.2.1.

PS: Thx for issue ;)
