### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by morder** [Arello-Mobile/Moxy#91]
gradle file
```
apply plugin: 'com.neenbedankt.android-apt'
...
compile 'com.android.support:appcompat-v7:25.0.1'
...
apt 'com.google.dagger:dagger-compiler:2.8'
compile 'com.google.dagger:dagger:2.8'
...
compile 'com.arello-mobile:moxy:1.4.5'
provided 'com.arello-mobile:moxy-compiler:1.4.5'
compile 'com.arello-mobile:moxy-android:1.4.5'
compile 'com.arello-mobile:moxy-app-compat:1.4.5'
```

crash
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/arellomobile/mvp/MoxyReflector;
at com.arellomobile.mvp.MvpProcessor.getMvpPresenters(MvpProcessor.java:82)
at com.arellomobile.mvp.MvpDelegate.onCreate(MvpDelegate.java:101)
at com.arellomobile.mvp.MvpAppCompatFragment.onCreate(MvpAppCompatFragment.java:23)
at some.package.BaseFragment.onCreate(BaseFragment.java:26)
```

**Comment by senneco** [comment]
Hi,

You can try use `apt'com.arello-mobile:moxy-compiler:1.4.5'` instead of `provided 'com.arello-mobile:moxy-compiler:1.4.5'`

**Comment by morder** [comment]
Already tryed, with no luck

**Comment by senneco** [comment]
Ok, have you some @InjectPresenter in your code? Or is it hello world project?

**Comment by morder** [comment]
Yes I have one @InjectPresenter

my structure is
```
public class ProfileFragment extends BaseFragment<ProfilePresenter> implements ProfileView {
    @InjectPresenter
    ProfilePresenter mPresenter;
...
}

public class BaseFragment<V extends BasePresenter> extends MvpAppCompatFragment implements View {}

@InjectViewState
public class ProfilePresenter extends BasePresenter<ProfileView> {}

@InjectViewState
public class  BasePresenter<T extends MvpView> extends MvpPresenter<T> {}

public interface ProfileView extends View {}
public interface View extends MvpView {}
```

**Comment by morder** [comment]
I think problem with MoxyReflector initialization, because I want to use Moxy with existing project and I integrate it to only one Fragment. So, now I extends MvpAppCompatFragment and MvpPresenter with my base classes, but I not inject presenters for all my fragments.
Now I get same error for other classes.

Maybe I can force to generate MoxyReflector class?

**Comment by senneco** [comment]
Maybe you are using `jack`? Currently `jack` has one throuble with moxy's annotation processor

**Comment by morder** [comment]
No, we don't use Jack, but retrolambda

**Comment by senneco** [comment]
Hmm, that's strange =) Could you check is file `app\build\generated\source\apt\debug\com\arellomobile\mvp\MoxyReflector.java` exists after rebuild project?

PS: Retrolambda is ok with Moxy
PPS: Could you run sample-github also?

**Comment by morder** [comment]
gradle
apt 'com.arello-mobile:moxy-compiler:1.4.5'

after "Rebuild project" where is no folder "app\build\generated\source\apt\debug\com\arellomobile" and in any other places

**Comment by senneco** [comment]
It's so strange :D could you give me more info about your project? Like full gradle config(all config files), screenshot of structure `app\build\generated\source\apt\debug`.

**Comment by morder** [comment]
I tried to move all our libraries and dependencies to test project, but test project is working with no problems.

app/build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'de.felixschulze.gradle.hockeyapp'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'com.jakewharton.hugo'
...
dependencies {
    compile files('libs/xxx.jar')
    compile files('libs/yyy.jar')
    //play-services
    compile 'com.google.android.gms:play-services-gcm:10.0.1'

    //dagger
    apt 'com.google.dagger:dagger-compiler:2.8'

    compile 'net.hockeyapp.android:HockeySDK:4.0.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile('io.branch.sdk.android:library:2.+') {
        exclude module: 'answers-shim'
    }
    compile 'com.github.clans:fab:1.6.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    compile 'net.danlew:android.joda:2.9.5.1'

    //support library
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:exifinterface:25.1.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:percent:25.0.1'

    //play-services
    compile 'com.google.android.gms:play-services-vision:10.0.1'

    compile 'com.google.code.gson:gson:2.4'

    //ui
    compile 'me.relex:circleindicator:1.1.5@aar'
    compile 'com.tonicartos:superslim:0.4.13'
    compile 'me.zhanghai.android.materialprogressbar:library:1.3.0'
    compile 'com.makeramen:roundedimageview:2.3.0'
    compile 'com.yqritc:android-scalablevideoview:1.0.4'

    //rx
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.2.6'
    compile 'com.jakewharton.rxbinding:rxbinding:1.0.0'

    //retrofit
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.6.0'

    // okhttp
    compile 'com.squareup.okhttp3:okhttp:3.6.0'

    //dagger
    apt 'com.google.dagger:dagger-compiler:2.8'
    compile 'com.google.dagger:dagger:2.8'

    // ORMLite
    compile 'com.j256.ormlite:ormlite-core:5.0'
    compile 'com.j256.ormlite:ormlite-android:5.0'

    // picasso
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'

    // facebook
    compile 'com.facebook.android:facebook-android-sdk:4.12.0'

    // analytics
    compile 'com.localytics.android:library:4.2.0'

    // cryptography
    compile 'com.madgag.spongycastle:prov:1.54.0.0'
    compile 'com.jakewharton.hugo:hugo-annotations:1.2.1'
}
```
and we use some native code (C++)

**Comment by senneco** [comment]
Sorry, but I don't see moxy-dependency at this `build.gradle`. Whatever, I don't see there some problems. I can advice you to change sample-github to your project, and then you can find difference -- it can help us ;)

**Comment by morder** [comment]
sorry, it copy-pasted from dev version without moxy

my moxy integration
```
    compile 'com.arello-mobile:moxy:1.4.5'
    apt 'com.arello-mobile:moxy-compiler:1.4.5'
    compile 'com.arello-mobile:moxy-android:1.4.5'
    compile 'com.arello-mobile:moxy-app-compat:1.4.5'
```

**Comment by morder** [comment]
So, problem was because we have module :core
And I add dependencies to this module

So I added
```
apt 'com.arello-mobile:moxy-compiler:1.4.5'
```
to app module, and the problem was solved :)

**Comment by Tolyas** [comment]
I've got the same problem if I using Kotlin in project.

For fix it use
`kapt 'com.arello-mobile:moxy-compiler:1.4.5'`
